@startuml
==start()阶段==

activate Bootstrap
Bootstrap->Bootstrap:start()
note over Bootstrap: start()
Bootstrap -> Catalina:start()反射
Catalina-> StandardServer:start()
StandardServer->StandardService:start()
       StandardService->StandardEngine:start()
            StandardEngine->StandardHost:start()
                StandardHost->StandardContext:start()
                        StandardContext->listener:listenerStart()
                        StandardContext->filter:filterStart()
                        StandardContext->Wapper:loadOnStartup(Container[] children)(Servlet)

                StandardHost->StandardPipeline:Host.StandardPipeline.start()
                        StandardPipeline->value:Host.StandardPipeline.start()
            StandardEngine->StandardPipeline:Engine.StandardPipeline.start()
                StandardPipeline->value:Engine.StandardPipeline.start()
       StandardService->StandardThreadExecutor:start()
       StandardService->Connector:start()

autonumber stop
@enduml